### ISSUE TITLE
PyPI docs formatting

### ISSUE THREAD

**Issue by zopyx** [pgjones/quart#3]
Please fix the formatting of the Readme file for 

https://pypi.python.org/pypi/Quart/0.4.0

**Comment by pgjones** [comment]
Yea, this is a pain that I can't seem to figure out. Any ideas on this (rst checkers note a minor warning)?

**Comment by claws** [comment]
The following checker command reports some issues:
```
$ python setup.py check --restructuredtext -s
warning: check: Duplicate implicit target name: "quart".
warning: check: Duplicate explicit target name: "docs".
```
Fixing these would be a good first step. The docs duplicate can be fixed by instead linking to the word deployment. The duplicate implicit quart link can be removed by instead linking the word Gitlab. This can be done by something like the following:

``` diff
$ git diff --patch README.rst
diff --git a/README.rst b/README.rst
index 8e79409..d871873 100644
--- a/README.rst
+++ b/README.rst
@@ -55,8 +55,8 @@ if the above is in a file called ``app.py`` it can be run as,
 
     $ python app.py
 
-To deploy in a production setting see the `docs
-<https://pgjones.gitlab.io/quart/deployment.html>`_.
+To deploy in a production setting see the `deployment
+<https://pgjones.gitlab.io/quart/deployment.html>`_ documentation.
 
 Features
 --------
@@ -72,10 +72,9 @@ support for,
 Contributing
 ------------
 
-Quart is developed on GitLab, see `Quart
-<https://gitlab.com/pgjones/quart>`_. You are very welcome to open
-`issues <https://gitlab.com/pgjones/quart/issues>`_ or propose `merge
-requests <https://gitlab.com/pgjones/quart/merge_requests>`_.
+Quart is developed on `GitLab <https://gitlab.com/pgjones/quart>`_. You 
+are very welcome to open `issues <https://gitlab.com/pgjones/quart/issues>`_ 
+or propose `merge requests <https://gitlab.com/pgjones/quart/merge_requests>`_.
```

With luck, fixing these issues might allow the RST content to be rendered properly on PyPI. If it doesn't, well, you've at least removed some warnings and cleaned up the docs. 😄

**Comment by pgjones** [comment]
Thanks @claws I've added your suggestion in 0e5ff32293c35c1ff060d23640dc41dc5a2487d9, lets hope it works in the next release 🤞

**Comment by pgjones** [comment]
Looks good, thanks.
